# Generated by Django 4.2.6 on 2023-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterHistory', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='countersnapshot',
            old_name='value',
            new_name='counterValue',
        ),
        migrations.RemoveField(
            model_name='countersnapshot',
            name='timestamp',
        ),
    ]
