# Generated by Django 4.2.6 on 2023-10-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_counterhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterhistory',
            old_name='counterHistory',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='countersnapshot',
            old_name='counterValue',
            new_name='counteredValue',
        ),
    ]
